name: Code Quality

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set up Python
              run: uv python install 3.11

            - name: Install dependencies
              run: uv sync --extra dev

            - name: Check code formatting with Black
              run: |
                  uv run black --check --diff src tests

            - name: Lint with flake8
              run: |
                  uv run flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
                  uv run flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

            - name: Type check with mypy
              run: |
                  uv run mypy src

    security:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set up Python
              run: uv python install 3.11

            - name: Install dependencies
              run: uv sync --extra dev

            - name: Run safety check
              run: |
                  uv add --dev safety
                  uv run safety check --json || true
