name: Scheduled Tasks

on:
    schedule:
        # 每天 UTC 時間 02:00 執行
        - cron: "0 2 * * *"
    workflow_dispatch: # 允許手動觸發

jobs:
    dependency-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set up Python
              run: uv python install 3.11

            - name: Install dependencies
              run: uv sync --extra dev

            - name: Check for outdated dependencies
              run: |
                  echo "檢查過期的依賴套件..."
                  uv add --dev pip-audit
                  uv run pip-audit --format=json --output=audit-report.json || true

            - name: Upload audit report
              uses: actions/upload-artifact@v4
              with:
                  name: dependency-audit-report
                  path: audit-report.json

    health-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set up Python
              run: uv python install 3.11

            - name: Install dependencies
              run: uv sync

            - name: Run health check
              run: |
                  echo "執行健康檢查..."
                  uv run python -m src.github_actions_practice.main hello --name "GitHub Actions" --count 1
                  uv run python -m src.github_actions_practice.main fetch --url "https://httpbin.org/json"
